In [2]:
import pandas as pd
import numpy as np
from scipy.io import savemat

In [2]:
metabolomics = pd.read_csv("IMOVNN_data/metabolomics.csv", index_col=0)

In [3]:
metagenomics = pd.read_csv("IMOVNN_data/metagenomics.csv", index_col=0)

In [4]:
metagenomics

k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii  \
External ID                                                                                                                                                    
PSM7J1BF                                                   0.0                                                                                                 
CSM7KORK                                                   0.0                                                                                                 
HSM7J4HS                                                   0.0                                                                                                 
MSM9VZNL                                                   0.0                                                                                                 
MSMB4LYB                                                   0.0                                                                                                 
...                                                        ...                                                                                                 
ESM5MEB9_P                                                 0.0                                                                                                 
PSMA266M                                                   0.0                                                                                                 
CSM9X22K                                                   0.0                                                                                                 
CSM7KOP2                                                   0.0                                                                                                 
HSM7CZ36                                                   0.0                                                                                                 

             k__Archaea|p__Euryarchaeota|c__Thermoplasmata|o__Methanomassiliicoccales|f__Methanomassiliicoccaceae|g__Methanomassiliicoccus|s__Candidatus_Methanomassiliicoccus_intestinalis  \
External ID                                                                                                                                                                                   
PSM7J1BF                                               0.00000                                                                                                                                
CSM7KORK                                               0.00000                                                                                                                                
HSM7J4HS                                               0.00000                                                                                                                                
MSM9VZNL                                               0.00000                                                                                                                                
MSMB4LYB                                               0.00000                                                                                                                                
...                                                        ...                                                                                                                                
ESM5MEB9_P                                             0.00000                                                                                                                                
PSMA266M                                               0.00000                                                                                                                                
CSM9X22K              

In [4]:
metatranscriptomics = pd.read_csv("IMOVNN_data/metatranscriptomics.csv", index_col=0)

In [5]:
metadata = pd.read_csv('IMOVNN_data/metadata.csv', index_col=0)

In [6]:
metatranscriptomics

1CMET2-PWY: N10-formyl-tetrahydrofolate biosynthesis  \
External ID                                                         
CSM5FZ3T_P                                            159.0120      
CSM5FZ46_P                                              0.0000      
CSM5FZ4C_P                                             76.6523      
CSM5FZ4G_P                                             28.7460      
CSM5FZ4K_P                                            108.0500      
...                                                        ...      
PSMA26A3                                               20.8237      
PSMB4MBK                                                0.0000      
PSMB4MBS                                               33.4581      
PSMB4MC5                                              113.4570      
PSMB4MC7                                               31.2157      

             3-HYDROXYPHENYLACETATE-DEGRADATION-PWY: 4-hydroxyphenylacetate degradation  \
External ID                                                                               
CSM5FZ3T_P                                                 0.0                            
CSM5FZ46_P                                                 0.0                            
CSM5FZ4C_P                                                 0.0                            
CSM5FZ4G_P                                                 0.0                            
CSM5FZ4K_P                                                 0.0                            
...                                                        ...                            
PSMA26A3                                                   0.0                            
PSMB4MBK                                                   0.0                            
PSMB4MBS                                                   0.0                            
PSMB4MC5                                                   0.0                            
PSMB4MC7                                                   0.0                            

             7ALPHADEHYDROX-PWY: cholate degradation (bacteria, anaerobic)  \
External ID                                                                  
CSM5FZ3T_P                                                 0.0               
CSM5FZ46_P                                                 0.0               
CSM5FZ4C_P                                                 0.0               
CSM5FZ4G_P                                                 0.0               
CSM5FZ4K_P                                                 0.0               
...                                                        ...               
PSMA26A3                                                   0.0               
PSMB4MBK                                                   0.0               
PSMB4MBS                                                   0.0               
PSMB4MC5                                                   0.0               
PSMB4MC7                                                   0.0               

             ALLANTOINDEG-PWY: superpathway of allantoin degradation in yeast  \
External ID                                                                     
CSM5FZ3T_P                                                 0.0                  
CSM5FZ46_P                                                 0.0                  
CSM5FZ4C_P                                                 0.0                  
CSM5FZ4G_P                                                 0.0                  
CSM5FZ4K_P                                                 0.0                  
...                                                        ...                  
PSMA26A3                                                   0.0                  
PSMB4MBK                                                   0.0                  
PSMB4MBS                                                   0.0                  
PSMB4MC5                 

In [7]:
def log(base,x):
    return np.log(x)/np.log(base)
metagenomics=log(2,2*metagenomics+0.00001)


In [8]:
metagenomics

k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii  \
External ID                                                                                                                                                    
PSM7J1BF                                             -16.60964                                                                                                 
CSM7KORK                                             -16.60964                                                                                                 
HSM7J4HS                                             -16.60964                                                                                                 
MSM9VZNL                                             -16.60964                                                                                                 
MSMB4LYB                                             -16.60964                                                                                                 
...                                                        ...                                                                                                 
ESM5MEB9_P                                           -16.60964                                                                                                 
PSMA266M                                             -16.60964                                                                                                 
CSM9X22K                                             -16.60964                                                                                                 
CSM7KOP2                                             -16.60964                                                                                                 
HSM7CZ36                                             -16.60964                                                                                                 

             k__Archaea|p__Euryarchaeota|c__Thermoplasmata|o__Methanomassiliicoccales|f__Methanomassiliicoccaceae|g__Methanomassiliicoccus|s__Candidatus_Methanomassiliicoccus_intestinalis  \
External ID                                                                                                                                                                                   
PSM7J1BF                                             -16.60964                                                                                                                                
CSM7KORK                                             -16.60964                                                                                                                                
HSM7J4HS                                             -16.60964                                                                                                                                
MSM9VZNL                                             -16.60964                                                                                                                                
MSMB4LYB                                             -16.60964                                                                                                                                
...                                                        ...                                                                                                                                
ESM5MEB9_P                                           -16.60964                                                                                                                                
PSMA266M                                             -16.60964                                                                                                                                
CSM9X22K              

In [9]:
metagenomics_external_id = metagenomics.index.tolist()
metabolomics_external_id = metabolomics.index.tolist()
metatranscriptomics_external_id = metatranscriptomics.index.tolist()
metadata_external_id = metadata.index.tolist()

In [10]:
available_omics = np.zeros((2891, 3))
for i in range(len(metadata_external_id)):
    if metadata_external_id[i] in metagenomics_external_id:
        available_omics[i, 0] = 1
    if metadata_external_id[i] in metabolomics_external_id:
        available_omics[i, 1] = 1
    if metadata_external_id[i] in metatranscriptomics_external_id:
        available_omics[i, 2] = 1
print(available_omics)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
savemat("available_omics.mat", {"available_omics": available_omics})

### omics

In [11]:
num_features = 578

# Identify missing values
metagenomics_missing_values = [id_ for id_ in metadata_external_id if id_ not in metagenomics.index]

# Create a DataFrame for the missing values with all features set to zero
metagenomics_missing_df = pd.DataFrame(
    np.zeros((len(metagenomics_missing_values), num_features)), 
    index=metagenomics_missing_values
)

# Ensure the columns of the missing_df match the original DataFrame
metagenomics_missing_df.columns = metagenomics.columns
metagenomics = pd.concat([metagenomics, metagenomics_missing_df])


print(metagenomics)

          k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii  \
PSM7J1BF                                          -16.60964                                                                                                 
CSM7KORK                                          -16.60964                                                                                                 
HSM7J4HS                                          -16.60964                                                                                                 
MSM9VZNL                                          -16.60964                                                                                                 
MSMB4LYB                                          -16.60964                                                                                                 
...                                                     ..

In [12]:
metagenomics = metagenomics.reindex(metadata_external_id)
print(metagenomics)

          k__Archaea|p__Euryarchaeota|c__Methanobacteria|o__Methanobacteriales|f__Methanobacteriaceae|g__Methanobrevibacter|s__Methanobrevibacter_smithii  \
206615                                                  0.0                                                                                                 
206614                                                  0.0                                                                                                 
206617                                                  0.0                                                                                                 
206619                                                  0.0                                                                                                 
206616                                                  0.0                                                                                                 
...                                                     ..

In [13]:
num_features = 596

# Identify missing values
metabolomics_missing_values = [id_ for id_ in metadata_external_id if id_ not in metabolomics.index]

# Create a DataFrame for the missing values with all features set to zero
metabolomics_missing_df = pd.DataFrame(
    np.zeros((len(metabolomics_missing_values), num_features)), 
    index=metabolomics_missing_values
)

# Ensure the columns of the missing_df match the original DataFrame
metabolomics_missing_df.columns = metabolomics.columns
metabolomics = pd.concat([metabolomics, metabolomics_missing_df])
metabolomics = metabolomics.reindex(metadata_external_id)


print(metabolomics)

          12.13-diHOME  9.10-diHOME  caproate  heptanoate  hydrocinnamate  \
206615             0.0          0.0       0.0         0.0             0.0   
206614             0.0          0.0       0.0         0.0             0.0   
206617             0.0          0.0       0.0         0.0             0.0   
206619             0.0          0.0       0.0         0.0             0.0   
206616             0.0          0.0       0.0         0.0             0.0   
...                ...          ...       ...         ...             ...   
CSM9X1Y7           0.0          0.0       0.0         0.0             0.0   
CSM79HNQ           0.0          0.0       0.0         0.0             0.0   
CSM7KOUP           0.0          0.0       0.0         0.0             0.0   
CSM9X23J           0.0          0.0       0.0         0.0             0.0   
HSM67VE2           0.0          0.0       0.0         0.0             0.0   

          mandelate  2-hydroxyoctanoate  3-hydroxyoctanoate  caprate  \
206

In [14]:
num_features = 421

# Identify missing values
metatranscriptomics_missing_values = [id_ for id_ in metadata_external_id if id_ not in metatranscriptomics.index]

# Create a DataFrame for the missing values with all features set to zero
metatranscriptomics_missing_df = pd.DataFrame(
    np.zeros((len(metatranscriptomics_missing_values), num_features)), 
    index=metatranscriptomics_missing_values
)

# Ensure the columns of the missing_df match the original DataFrame
metatranscriptomics_missing_df.columns = metatranscriptomics.columns
metatranscriptomics = pd.concat([metatranscriptomics, metatranscriptomics_missing_df])
metatranscriptomics = metatranscriptomics.reindex(metadata_external_id)


print(metatranscriptomics)

          1CMET2-PWY: N10-formyl-tetrahydrofolate biosynthesis  \
206615                                                  0.0      
206614                                                  0.0      
206617                                                  0.0      
206619                                                  0.0      
206616                                                  0.0      
...                                                     ...      
CSM9X1Y7                                                0.0      
CSM79HNQ                                                0.0      
CSM7KOUP                                                0.0      
CSM9X23J                                                0.0      
HSM67VE2                                                0.0      

          3-HYDROXYPHENYLACETATE-DEGRADATION-PWY: 4-hydroxyphenylacetate degradation  \
206615                                                  0.0                            
206614                         

In [15]:
metatranscriptomics

1CMET2-PWY: N10-formyl-tetrahydrofolate biosynthesis  \
206615                                                  0.0      
206614                                                  0.0      
206617                                                  0.0      
206619                                                  0.0      
206616                                                  0.0      
...                                                     ...      
CSM9X1Y7                                                0.0      
CSM79HNQ                                                0.0      
CSM7KOUP                                                0.0      
CSM9X23J                                                0.0      
HSM67VE2                                                0.0      

          3-HYDROXYPHENYLACETATE-DEGRADATION-PWY: 4-hydroxyphenylacetate degradation  \
206615                                                  0.0                            
206614                                                  0.0                            
206617                                                  0.0                            
206619                                                  0.0                            
206616                                                  0.0                            
...                                                     ...                            
CSM9X1Y7                                                0.0                            
CSM79HNQ                                                0.0                            
CSM7KOUP                                                0.0                            
CSM9X23J                                                0.0                            
HSM67VE2                                                0.0                            

          7ALPHADEHYDROX-PWY: cholate degradation (bacteria, anaerobic)  \
206615                                                  0.0               
206614                                                  0.0               
206617                                                  0.0               
206619                                                  0.0               
206616                                                  0.0               
...                                                     ...               
CSM9X1Y7                                                0.0               
CSM79HNQ                                                0.0               
CSM7KOUP                                                0.0               
CSM9X23J                                                0.0               
HSM67VE2                                                0.0               

          ALLANTOINDEG-PWY: superpathway of allantoin degradation in yeast  \
206615                                                  0.0                  
206614                                                  0.0                  
206617                                                  0.0                  
206619                                                  0.0                  
206616                                                  0.0                  
...                                                     ...                  
CSM9X1Y7                                                0.0                  
CSM79HNQ                                                0.0                  
CSM7KOUP                                                0.0                  
CSM9X23J                                                0.0                  
HSM67VE2                                                0.0                  

          ANAEROFRUCAT-PWY: homolactic fermentation  \
206615                                          0.0   
206614                                          0.0   
206617                                          0.0   
206619                                          0.0   
206616                                         

In [16]:
def normalize_column(column):
    return (column - column.min()) / (column.max() - column.min())

# Apply normalization to each column
metagenomics = metagenomics.apply(normalize_column)
metabolomics = metabolomics.apply(normalize_column)
metatranscriptomics = metatranscriptomics.apply(normalize_column)

In [20]:
metabolomics.applymap(lambda x: x != 0 and not pd.isna(x)).sum()

12.13-diHOME           546
9.10-diHOME            546
caproate               511
heptanoate             239
hydrocinnamate         546
                      ... 
sphingosine-isomer1    536
sphingosine-isomer2    546
sphingosine-isomer3    545
C14:0 SM               305
C16:0 SM.1             531
Length: 596, dtype: int64

In [19]:
metagenomics.fillna(0, inplace=True)
metabolomics.fillna(0, inplace=True)
metatranscriptomics.fillna(0, inplace=True)

In [21]:
arr1 = metagenomics.to_numpy()
arr2 = metabolomics.to_numpy()
arr3 = metatranscriptomics.to_numpy()

In [22]:
savemat('metagenomics_data.mat', {'metagenomics_X': arr1})
savemat('metabolomics_data.mat', {'metabolomics_X': arr2})
savemat('metatranscriptomics_data.mat', {'metatranscriptomics_X': arr2})